version: '3.8'

services:
  bloss_postgres:
    container_name: bloss_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: bloss
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $db_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      interval: 1m
      timeout: 10s
      retries: 2

  bloss:
    container_name: bloss
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - bloss_postgres
    links:
      - bloss_postgres
    environment:
      db_host: jdbc:postgresql://bloss_postgres:5432/
      db_username: postgres
      db_password: $db_password
      SECURITY_SECRET: $SECURITY_SECRET

volumes:
  postgres_data:
    driver: local
