server:
  port: 8080

spring:
  datasource:
    url: ${db_host}
    driver-class-name: org.postgresql.Driver
    username: ${db_username}
    password: ${db_password}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

app:
  security:
    tokenSecret: ${SECURITY_SECRET}
    tokenExpirationMSec: 864000000
    tokenPrefix: "Bearer "
    headerString: "Authorization"
    cors:
      allowedOrigins: http://localhost:8080, http://20.67.104.18:8080
      maxAge: 3600
  rmq:
    host: ${rmq_host}
    port: ${rmq_port}
    username: ${rmq_username}
    password: ${rmq_password}

camunda:
  bpm:
    admin-user:
      password: admin
      id: admin
      first-name: Admin
      last-name: Admin
      email: admin@admin.com
