server:
  port: 8080

spring:
  datasource:
    url: "${db_host}/bloss"
    driver-class-name: org.postgresql.Driver
    username: ${db_username}
    password: ${db_password}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  kafka:
    bootstrap-servers: "::1:9092"
    template:
      default-topic: "user-data-request"

app:
  security:
    tokenSecret: ${SECURITY_SECRET}
    tokenExpirationMSec: 864000000
    tokenPrefix: "Bearer "
    headerString: "Authorization"
    cors:
      allowedOrigins: http://localhost:8080, http://20.67.104.18:8080
      maxAge: 3600
  schedule:
    scheduleToHidePosts: "0 0 2 * * *"
    millisecondsToHideByCreationDate: 2592000000
    millisecondsToHideByLastWatchedDate: 604800000
