server:
  port: 8081

spring:
  datasource:
    url: "${db_host}/bloss"
    driver-class-name: org.postgresql.Driver
    username: ${db_username}
    password: ${db_password}
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: ${email_username}
    password: ${email_password}

app:
  rmq:
    host: "[::1]"
    port: 5672
    username: "guest"
    password: "guest"
